baseURL: https://mark26745.github.io/gevsite.github.io/
languageCode: en-us
title: Geviton
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  logo: /images/logos/logo.svg
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description: Geviton.co.ke site demo
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
    link: /gevsite.github.io/
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: "Ideation. Prototyping. Production."
    # Hero subtitle (optional)
    subtitle: Breathe Life Into Your Ideas. 
    # Button text
    # buttontext: Get started
    # Where the main hero button links to
    # buttonlink: "#"
    # Hero image (from static/images/___)
    image: logos/geviton-favicon.png
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Home 
    url: /gevsite.github.io/
  - title: About Us 
    url: /gevsite.github.io/#about
  - title: Portfolio 
    url: /gevsite.github.io/portfolio
  - title: Services 
    url: /gevsite.github.io/#services
  # - title: Contact Us 
  #   url: /
  #   button: true

  partners:
    enabled: true

  services:
    title: 
    subtitle: We are a professional electronic design and manufacturing company that has been solving engineering and manufacturing challenges for customers operating in different markets. 
    tiles:
    - title: Ideation 
      icon:  images/illustrations/light-bulb-svgrepo-com.svg 
      text: We collaborate with startups, enterprises and innovators across different sectors to generate feasible product ideas with clear development and manufacturing deliverables 

    - title: Prototyping 
      icon:  images/illustrations/gear-svgrepo-com.svg 
      text: We leverage our extensive experience of the best hardware platforms for affordable prototyping/RnD costs with very fair mass production clauses 

    - title: Mass Production 
      icon:  images/illustrations/factory-svgrepo-com.svg 
      text: We have good working relations with PCBA, product assembly factories and key electronic component distributors that allows to plan and mesh our mass production runs seamlessly with product timelines 

  about:
    title: About Us 
    subtitle: We are the rocket fuel that will propel the hardware culture in Africa. 
    features:
    - title: Mission 
      text: Our mission is to provide innovative and cost-effective solutions to our customers' engineering and manufacturing challenges, enabling them to bring their ideas to market quickly and efficiently. 
    - title: Vision
      text: Our vision is to be the go-to partner for businesses seeking reliable and comprehensive electronic design and manufacturing services, helping them stay competitive and profitable in a rapidly changing market. 

  portfolio:
    title: One platform
    subtitle: To rule them all
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"

  testimonials:
    title: Our Clients love us!
    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: Irma Walters
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Accountant
      img: 1
    - name: John Bradley
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Financial Analyst
      img: 2
    - name: Gary Blackman
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: HR Manager
      img: 3

  forms: true

  footer:
    # Logo (from /images/logos/___)
    logo: logo.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://www.linkedin.com/company/geviton-enterprises-limited/ 
      icon: linkedin 
    - link: https://twitter.com/gevitonltd 
      icon: twitter 

    contacts:
      title: Our Contacts 
      mobile_1: +254724149923 
      mobile_2: +254713932088
      email: info@geviton.co.ke 

    quicklinks:
      sitemap:
        title: "Sitemap"
        links:
        - text: Home 
          link: /gevsite.github.io/
        - text: About Us 
          link: /gevsite.github.io/#about
        - text: Portfolio 
          link: /gevsite.github.io/portfolio
        - text: Services 
          link: /gevsite.github.io/#services
      contacts:
        title: Our Contacts
        links: 
          - text: "+254724149923"
            link: "tel:254724149923" 
          - text: "+254713932088"
            link: "tel:254713932088"
          - text: info@geviton.co.ke
            link: mailto:info@geviton.co.ke 